// Generated by scripts/generate_workflow_types.py from the Factory native schema.
// Do not hand-edit. Native validation additionally enforces references and topology.
export type Locator = string;

export type Ref = string;

export type NonEmpty = string;

export type RefSet = ReadonlyArray<Ref>;

export type LocatorSet = ReadonlyArray<Locator>;

export type TextSet = ReadonlyArray<NonEmpty>;

export type WorkflowSourceProvenance = {
  readonly ref: string;
  readonly revision: NonEmpty;
  readonly digest: string;
  readonly temporalRef?: string;
  readonly flowRef?: string;
  readonly authoring?: AuthoredBasis;
};

export type AgentRequirements = {
  readonly agentRefs?: RefSet;
  readonly agentSetRefs?: RefSet;
  readonly agencyRefs?: RefSet;
};

export type WorkflowUnitSource = {
  readonly key: Locator;
  readonly developmentalConcern: NonEmpty;
  readonly requiredDifference: NonEmpty;
  readonly returnContract: NonEmpty;
  readonly subjectRef: Ref;
  readonly basisRevision: NonEmpty;
  readonly agentRequirements: AgentRequirements;
  readonly praxisRefs: RefSet;
  readonly capabilityRefs: RefSet;
  readonly dependencies?: LocatorSet;
  readonly independenceFrom?: LocatorSet;
  readonly permittedEffects: TextSet;
  readonly verificationObligations: TextSet;
  readonly returnAddress: Ref;
  readonly stopConditions: NonEmpty;
  readonly escalationConditions: NonEmpty;
};

export type WorkflowBarrierSource = {
  readonly key: Locator;
  readonly waitsFor: LocatorSet;
  readonly releases: LocatorSet;
};

export type WorkflowNestingSource = {
  readonly parent: Locator;
  readonly child: Locator;
};

export type SourceLocation = {
  readonly file: string;
  readonly line: number;
  readonly column: number;
  readonly byteOffset: number;
};

export type ModuleBasis = {
  readonly path: string;
  readonly digest: string;
  readonly bytes: number;
};

export type SourcePointer = {
  readonly ref: string;
  readonly revision: string;
  readonly digest: string;
};

export type AuthoredBasis = {
  readonly contract: "factory.authored-workflow-basis/v1";
  readonly compiler: string;
  readonly compilerDigest: string;
  readonly entry: string;
  readonly revision: string;
  readonly bundleDigest: string;
  readonly modules: Readonly<Record<string, ModuleBasis>>;
  readonly locations: Readonly<Record<string, SourceLocation>>;
  readonly successorOf?: SourcePointer;
};

export type WorkflowSource = {
  readonly schemaVersion: "factory.agent-workflow-source/v1";
  readonly coordinationContract: "factory.bounded-coordination/v1";
  readonly source: WorkflowSourceProvenance;
  readonly workflowKey: Locator;
  readonly units: ReadonlyArray<WorkflowUnitSource>;
  readonly barriers?: ReadonlyArray<WorkflowBarrierSource>;
  readonly nesting?: ReadonlyArray<WorkflowNestingSource>;
};

/** Native exact-edition revision is explicit. Factory computes digest and byte provenance. */
export type WorkflowDefinition = Omit<WorkflowSource, "schemaVersion" | "coordinationContract" | "source"> & {
  readonly source: Omit<WorkflowSourceProvenance, "digest" | "authoring">;
  readonly schemaVersion?: WorkflowSource["schemaVersion"];
  readonly coordinationContract?: WorkflowSource["coordinationContract"];
};
export declare function defineWorkflow<const T extends WorkflowDefinition>(value: T): T;
export declare function unit<const T extends WorkflowUnitSource>(value: T): T;
export declare function barrier<const T extends WorkflowBarrierSource>(value: T): T;
export declare function nesting<const T extends WorkflowNestingSource>(value: T): T;
