#!/usr/bin/env python3
"""Project Factory's owning JSON schema to the installed TypeScript data API.

--check is a contract-drift gate. This is generation, not a second schema.
Native structural, identity, topology and authority validation remains Rust-owned.
"""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / 'contracts/factory/agent-workflow-source.schema.json'
OUTPUT = ROOT / 'factory/workflow-sdk/index.d.ts'
NAMES = {'sourceProvenance':'WorkflowSourceProvenance','unit':'WorkflowUnitSource',
         'agentRequirements':'AgentRequirements','barrier':'WorkflowBarrierSource',
         'nesting':'WorkflowNestingSource'}
def name(s):
    return NAMES.get(s, s[0].upper()+s[1:])
def emit(s):
    if '$ref' in s: return name(s['$ref'].split('/')[-1])
    if 'const' in s: return json.dumps(s['const'])
    if 'enum' in s: return ' | '.join(json.dumps(x) for x in s['enum'])
    if 'allOf' in s: return ' & '.join(emit(x) for x in s['allOf'] if '$ref' in x or 'type' in x) or 'unknown'
    t=s.get('type')
    if t=='string':return 'string'
    if t in ('integer','number'):return 'number'
    if t=='boolean':return 'boolean'
    if t=='array':return 'ReadonlyArray<'+emit(s['items'])+'>'
    if t=='object':
        if 'properties' not in s: return 'Readonly<Record<string, '+emit(s['additionalProperties'])+'>>'
        required=set(s.get('required',[]))
        fields=['  readonly '+k+('' if k in required else '?')+': '+emit(v)+';' for k,v in s['properties'].items()]
        return '{\n'+'\n'.join(fields)+'\n}'
    raise ValueError('Unsupported schema construct: '+repr(s))
def generate():
    schema=json.loads(SCHEMA.read_text())
    text='// Generated by scripts/generate_workflow_types.py from the Factory native schema.\n// Do not hand-edit. Native validation additionally enforces references and topology.\n'
    for key,value in schema['$defs'].items():text+='export type '+name(key)+' = '+emit(value)+';\n\n'
    text+='export type WorkflowSource = '+emit(schema)+';\n\n'
    text+='''/** Native exact-edition revision is explicit. Factory computes digest and byte provenance. */
export type WorkflowDefinition = Omit<WorkflowSource, "schemaVersion" | "coordinationContract" | "source"> & {
  readonly source: Omit<WorkflowSourceProvenance, "digest" | "authoring">;
  readonly schemaVersion?: WorkflowSource["schemaVersion"];
  readonly coordinationContract?: WorkflowSource["coordinationContract"];
};
export declare function defineWorkflow<const T extends WorkflowDefinition>(value: T): T;
export declare function unit<const T extends WorkflowUnitSource>(value: T): T;
export declare function barrier<const T extends WorkflowBarrierSource>(value: T): T;
export declare function nesting<const T extends WorkflowNestingSource>(value: T): T;
'''
    return text
if __name__=='__main__':
    args=argparse.ArgumentParser(description=__doc__);args.add_argument('--check',action='store_true');opts=args.parse_args()
    text=generate()
    if opts.check:
        if not OUTPUT.exists() or OUTPUT.read_text()!=text:raise SystemExit('Factory workflow types drifted; run scripts/generate_workflow_types.py')
        print('Factory TypeScript types match the owning native schema')
    else:OUTPUT.write_text(text)
